dist: xenial
language: java

addons:
  apt:
    packages:
      - libboost-all-dev
      - libevent-dev
      - libssl-dev

before_install:
  # install Apache Thrift
  - git clone --branch 0.13.0 https://github.com/apache/thrift.git
  - ./bootstrap.sh
  - ./configure --without-ruby --without-cpp --without-go --without-php --without-python --without-nodejs
  - sudo make -j2 install
