dist: bionic
language: java

addons:
  apt:
    packages:
      - ruby-full
      - libboost-all-dev
      - libevent-dev
      - libssl-dev

before_install:
  # install Apache Thrift
  - wget https://www-eu.apache.org/dist/thrift/0.12.0/thrift-0.12.0.tar.gz
  - tar xzf thrift-0.12.0.tar.gz
  - (cd thrift-0.12.0 && ./configure && sudo make -j2 install)
